# Generated by Django 2.1.1 on 2018-09-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('plot', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('rating', models.IntegerField(choices=[(0, 'NR - Sin Clasificar'), (1, 'G - Audiencia General'), (2, 'PG - Bajo supervision de los padres'), (3, 'R - Restringido')], default=0)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
